import type { Metadata } from "next";
import localFont from "next/font/local";
// import "./globals.css";
import AuthProvider from "../../context/AuthProvider";
import Sidebar from "../../components/Sidebar";
import Navbar from "../../components/Navbar";


// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
// });

export const metadata: Metadata = {
  title: "PayWallet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <body className={``}>
      <div>
      <Navbar/>
      <div className="flex h-screen">
          <Sidebar/>
          <div className="p-6 w-full">
             {children}
          </div>
          
      </div>
     
      </div>
      </body>
      </AuthProvider>
    </html>
  );
}